baseURL: "https://www.horaciomorenom.me/" 
title: Horacio Moreno Montañes
paginate: 20
theme: PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: Data
          url: data/
          weight: 3 
        - name: Newsletter
          url: https://www.horaciomorenom.me/
          weight: 4


params:
    description: "I am an undergraduate student studying Applied Mathematics and Interdisiplinary Physics."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Horacio Moreno Montañes
          subtitle: "I am an undergraduate student studing Applied Mathematics and Interdisciplinary Physics at the University of Michigan. I am interested in nonlinear systems and plasma and fluid dynamics. "
          imageUrl: "picture.jpg"
          imageWidth: 350
          imageHeight: 350
          imageTitle: Horacio
          buttons:
            - name: Projects
              url: projects/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Newsletter
              url: https://pmichaillat.substack.com
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:hmorenom@umich.com
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: YouTube
          url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Substack
          url: https://pmichaillat.substack.com
        - name: Twitter
          url: https://twitter.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Horacio"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
